//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Web.Mvc.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MvcResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Web.Mvc.Properties.MvcResources", typeof(MvcResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The current request for action &apos;{0}&apos; on controller type &apos;{1}&apos; is ambiguous between the following action methods:{2} 的本地化字符串。
        /// </summary>
        internal static string ActionMethodSelector_AmbiguousMatch {
            get {
                return ResourceManager.GetString("ActionMethodSelector_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} on type {1} 的本地化字符串。
        /// </summary>
        internal static string ActionMethodSelector_AmbiguousMatchType {
            get {
                return ResourceManager.GetString("ActionMethodSelector_AmbiguousMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value must be greater than or equal to {0}. 的本地化字符串。
        /// </summary>
        internal static string ArgumentMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ArgumentMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The asynchronous action method &apos;{0}&apos; cannot be executed synchronously. 的本地化字符串。
        /// </summary>
        internal static string AsyncActionDescriptor_CannotExecuteSynchronously {
            get {
                return ResourceManager.GetString("AsyncActionDescriptor_CannotExecuteSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lookup for method &apos;{0}&apos; on controller type &apos;{1}&apos; failed because of an ambiguity between the following methods:{2} 的本地化字符串。
        /// </summary>
        internal static string AsyncActionMethodSelector_AmbiguousMethodMatch {
            get {
                return ResourceManager.GetString("AsyncActionMethodSelector_AmbiguousMethodMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not locate a method named &apos;{0}&apos; on controller type {1}. 的本地化字符串。
        /// </summary>
        internal static string AsyncActionMethodSelector_CouldNotFindMethod {
            get {
                return ResourceManager.GetString("AsyncActionMethodSelector_CouldNotFindMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided IAsyncResult has already been consumed. 的本地化字符串。
        /// </summary>
        internal static string AsyncCommon_AsyncResultAlreadyConsumed {
            get {
                return ResourceManager.GetString("AsyncCommon_AsyncResultAlreadyConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The controller of type &apos;{0}&apos; must subclass AsyncController or implement the IAsyncManagerContainer interface. 的本地化字符串。
        /// </summary>
        internal static string AsyncCommon_ControllerMustImplementIAsyncManagerContainer {
            get {
                return ResourceManager.GetString("AsyncCommon_ControllerMustImplementIAsyncManagerContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided IAsyncResult is not valid for this method. 的本地化字符串。
        /// </summary>
        internal static string AsyncCommon_InvalidAsyncResult {
            get {
                return ResourceManager.GetString("AsyncCommon_InvalidAsyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The timeout value must be non-negative or Timeout.Infinite. 的本地化字符串。
        /// </summary>
        internal static string AsyncCommon_InvalidTimeout {
            get {
                return ResourceManager.GetString("AsyncCommon_InvalidTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not infer area name for the controller &apos;{0}&apos; because it does not have a namespace. 的本地化字符串。
        /// </summary>
        internal static string AttributeRouting_CouldNotInferAreaNameFromMissingNamespace {
            get {
                return ResourceManager.GetString("AttributeRouting_CouldNotInferAreaNameFromMissingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AuthorizeAttribute cannot be used within a child action caching block. 的本地化字符串。
        /// </summary>
        internal static string AuthorizeAttribute_CannotUseWithinChildActionCache {
            get {
                return ResourceManager.GetString("AuthorizeAttribute_CannotUseWithinChildActionCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The action &apos;{0}&apos; is accessible only by a child request. 的本地化字符串。
        /// </summary>
        internal static string ChildActionOnlyAttribute_MustBeInChildRequest {
            get {
                return ResourceManager.GetString("ChildActionOnlyAttribute_MustBeInChildRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be a date. 的本地化字符串。
        /// </summary>
        internal static string ClientDataTypeModelValidatorProvider_FieldMustBeDate {
            get {
                return ResourceManager.GetString("ClientDataTypeModelValidatorProvider_FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The field {0} must be a number. 的本地化字符串。
        /// </summary>
        internal static string ClientDataTypeModelValidatorProvider_FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("ClientDataTypeModelValidatorProvider_FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No route in the route table matches the supplied values. 的本地化字符串。
        /// </summary>
        internal static string Common_NoRouteMatched {
            get {
                return ResourceManager.GetString("Common_NoRouteMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string Common_NullOrEmpty {
            get {
                return ResourceManager.GetString("Common_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The partial view &apos;{0}&apos; was not found or no view engine supports the searched locations. The following locations were searched:{1} 的本地化字符串。
        /// </summary>
        internal static string Common_PartialViewNotFound {
            get {
                return ResourceManager.GetString("Common_PartialViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property &apos;{0}&apos; cannot be null or empty. 的本地化字符串。
        /// </summary>
        internal static string Common_PropertyCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Common_PropertyCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property {0}.{1} could not be found. 的本地化字符串。
        /// </summary>
        internal static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False 的本地化字符串。
        /// </summary>
        internal static string Common_TriState_False {
            get {
                return ResourceManager.GetString("Common_TriState_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Set 的本地化字符串。
        /// </summary>
        internal static string Common_TriState_NotSet {
            get {
                return ResourceManager.GetString("Common_TriState_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True 的本地化字符串。
        /// </summary>
        internal static string Common_TriState_True {
            get {
                return ResourceManager.GetString("Common_TriState_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} must derive from {1} 的本地化字符串。
        /// </summary>
        internal static string Common_TypeMustDriveFromType {
            get {
                return ResourceManager.GetString("Common_TypeMustDriveFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is invalid. 的本地化字符串。
        /// </summary>
        internal static string Common_ValueNotValidForProperty {
            get {
                return ResourceManager.GetString("Common_ValueNotValidForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The view &apos;{0}&apos; or its master was not found or no view engine supports the searched locations. The following locations were searched:{1} 的本地化字符串。
        /// </summary>
        internal static string Common_ViewNotFound {
            get {
                return ResourceManager.GetString("Common_ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; and &apos;{1}&apos; do not match. 的本地化字符串。
        /// </summary>
        internal static string CompareAttribute_MustMatch {
            get {
                return ResourceManager.GetString("CompareAttribute_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find a property named {0}. 的本地化字符串。
        /// </summary>
        internal static string CompareAttribute_UnknownProperty {
            get {
                return ResourceManager.GetString("CompareAttribute_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A public action method &apos;{0}&apos; was not found on controller &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Controller_UnknownAction {
            get {
                return ResourceManager.GetString("Controller_UnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No matching action was found on controller &apos;{0}&apos;. This can happen when a controller uses RouteAttribute for routing, but no action on that controller matches the request. 的本地化字符串。
        /// </summary>
        internal static string Controller_UnknownAction_NoActionName {
            get {
                return ResourceManager.GetString("Controller_UnknownAction_NoActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model of type &apos;{0}&apos; could not be updated. 的本地化字符串。
        /// </summary>
        internal static string Controller_UpdateModel_UpdateUnsuccessful {
            get {
                return ResourceManager.GetString("Controller_UpdateModel_UpdateUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model of type &apos;{0}&apos; is not valid. 的本地化字符串。
        /// </summary>
        internal static string Controller_Validate_ValidationFailed {
            get {
                return ResourceManager.GetString("Controller_Validate_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot execute Controller with a null HttpContext. 的本地化字符串。
        /// </summary>
        internal static string ControllerBase_CannotExecuteWithNullHttpContext {
            get {
                return ResourceManager.GetString("ControllerBase_CannotExecuteWithNullHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A single instance of controller &apos;{0}&apos; cannot be used to handle multiple requests. If a custom controller factory is in use, make sure that it creates a new instance of the controller for each request. 的本地化字符串。
        /// </summary>
        internal static string ControllerBase_CannotHandleMultipleRequests {
            get {
                return ResourceManager.GetString("ControllerBase_CannotHandleMultipleRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred when trying to create the IControllerFactory &apos;{0}&apos;. Make sure that the controller factory has a public parameterless constructor. 的本地化字符串。
        /// </summary>
        internal static string ControllerBuilder_ErrorCreatingControllerFactory {
            get {
                return ResourceManager.GetString("ControllerBuilder_ErrorCreatingControllerFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The IControllerFactory &apos;{0}&apos; did not return a controller for the name &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ControllerBuilder_FactoryReturnedNull {
            get {
                return ResourceManager.GetString("ControllerBuilder_FactoryReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The controller factory type &apos;{0}&apos; must implement the IControllerFactory interface. 的本地化字符串。
        /// </summary>
        internal static string ControllerBuilder_MissingIControllerFactory {
            get {
                return ResourceManager.GetString("ControllerBuilder_MissingIControllerFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The view found at &apos;{0}&apos; was not created. 的本地化字符串。
        /// </summary>
        internal static string CshtmlView_ViewCouldNotBeCreated {
            get {
                return ResourceManager.GetString("CshtmlView_ViewCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The view at &apos;{0}&apos; must derive from WebViewPage, or WebViewPage&lt;TModel&gt;. 的本地化字符串。
        /// </summary>
        internal static string CshtmlView_WrongViewBase {
            get {
                return ResourceManager.GetString("CshtmlView_WrongViewBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has a DisplayColumn attribute for {1}, but property {1} does not exist. 的本地化字符串。
        /// </summary>
        internal static string DataAnnotationsModelMetadataProvider_UnknownProperty {
            get {
                return ResourceManager.GetString("DataAnnotationsModelMetadataProvider_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} has a DisplayColumn attribute for {1}, but property {1} does not have a public getter. 的本地化字符串。
        /// </summary>
        internal static string DataAnnotationsModelMetadataProvider_UnreadableProperty {
            get {
                return ResourceManager.GetString("DataAnnotationsModelMetadataProvider_UnreadableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} must have a public constructor which accepts three parameters of types {1}, {2}, and {3} 的本地化字符串。
        /// </summary>
        internal static string DataAnnotationsModelValidatorProvider_ConstructorRequirements {
            get {
                return ResourceManager.GetString("DataAnnotationsModelValidatorProvider_ConstructorRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} must have a public constructor which accepts two parameters of types {1} and {2}. 的本地化字符串。
        /// </summary>
        internal static string DataAnnotationsModelValidatorProvider_ValidatableConstructorRequirements {
            get {
                return ResourceManager.GetString("DataAnnotationsModelValidatorProvider_ValidatableConstructorRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.{2}{2}The request for &apos;{0}&apos; has found the following matching controllers:{1} 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_ControllerNameAmbiguous_WithoutRouteUrl {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ControllerNameAmbiguous_WithoutRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple types were found that match the controller named &apos;{0}&apos;. This can happen if the route that services this request (&apos;{1}&apos;) does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the &apos;MapRoute&apos; method that takes a &apos;namespaces&apos; parameter.{3}{3}The request for &apos;{0}&apos; has found the following matching controllers:{2} 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_ControllerNameAmbiguous_WithRouteUrl {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ControllerNameAmbiguous_WithRouteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple controller types were found that match the URL. This can happen if attribute routes on multiple controllers match the requested URL.{1}{1}The request has found the following matching controller types: {0} 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_DirectRouteAmbiguous {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_DirectRouteAmbiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred when trying to create a controller of type &apos;{0}&apos;. Make sure that the controller has a parameterless public constructor. 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_ErrorCreatingController {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_ErrorCreatingController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The controller for path &apos;{0}&apos; was not found or does not implement IController. 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_NoControllerFound {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_NoControllerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The controller type &apos;{0}&apos; must implement IController. 的本地化字符串。
        /// </summary>
        internal static string DefaultControllerFactory_TypeDoesNotSubclassControllerBase {
            get {
                return ResourceManager.GetString("DefaultControllerFactory_TypeDoesNotSubclassControllerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The constructor to use for activating the constraint type &apos;{0}&apos; is ambiguous. Multiple constructors were found with the following number of parameters: {1}. 的本地化字符串。
        /// </summary>
        internal static string DefaultInlineConstraintResolver_AmbiguousCtors {
            get {
                return ResourceManager.GetString("DefaultInlineConstraintResolver_AmbiguousCtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find a constructor for constraint type &apos;{0}&apos; with the following number of parameters: {1}. 的本地化字符串。
        /// </summary>
        internal static string DefaultInlineConstraintResolver_CouldNotFindCtor {
            get {
                return ResourceManager.GetString("DefaultInlineConstraintResolver_CouldNotFindCtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The constraint type &apos;{0}&apos; which is mapped to constraint key &apos;{1}&apos; must implement the IRouteConstraint interface. 的本地化字符串。
        /// </summary>
        internal static string DefaultInlineConstraintResolver_TypeNotConstraint {
            get {
                return ResourceManager.GetString("DefaultInlineConstraintResolver_TypeNotConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value &apos;{0}&apos; is not valid for {1}. 的本地化字符串。
        /// </summary>
        internal static string DefaultModelBinder_ValueInvalid {
            get {
                return ResourceManager.GetString("DefaultModelBinder_ValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value is required. 的本地化字符串。
        /// </summary>
        internal static string DefaultModelBinder_ValueRequired {
            get {
                return ResourceManager.GetString("DefaultModelBinder_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The number of ticks for the TimeSpan value must be greater than or equal to 0. 的本地化字符串。
        /// </summary>
        internal static string DefaultViewLocationCache_NegativeTimeSpan {
            get {
                return ResourceManager.GetString("DefaultViewLocationCache_NegativeTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} does not appear to implement Microsoft.Practices.ServiceLocation.IServiceLocator. 的本地化字符串。
        /// </summary>
        internal static string DependencyResolver_DoesNotImplementICommonServiceLocator {
            get {
                return ResourceManager.GetString("DependencyResolver_DoesNotImplementICommonServiceLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current request is ambiguous between the following action methods:{0} 的本地化字符串。
        /// </summary>
        internal static string DirectRoute_AmbiguousMatch {
            get {
                return ResourceManager.GetString("DirectRoute_AmbiguousMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A direct route for an action method cannot use the parameter &apos;action&apos;. Specify a literal path in place of this parameter to create a route to the action. 的本地化字符串。
        /// </summary>
        internal static string DirectRoute_InvalidParameter_Action {
            get {
                return ResourceManager.GetString("DirectRoute_InvalidParameter_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A direct route cannot use the parameter &apos;controller&apos;. Specify a literal path in place of this parameter to create a route to a controller. 的本地化字符串。
        /// </summary>
        internal static string DirectRoute_InvalidParameter_Controller {
            get {
                return ResourceManager.GetString("DirectRoute_InvalidParameter_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The route does not have any associated action descriptors. Routing requires that each direct route map to a non-empty set of actions. 的本地化字符串。
        /// </summary>
        internal static string DirectRoute_MissingActionDescriptors {
            get {
                return ResourceManager.GetString("DirectRoute_MissingActionDescriptors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The route does not have an associated controller descriptor. Routing requires that each direct route map to a single controller. 的本地化字符串。
        /// </summary>
        internal static string DirectRoute_MissingControllerDescriptor {
            get {
                return ResourceManager.GetString("DirectRoute_MissingControllerDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The route does not have an associated controller type. Routing requires that each direct route map to a single controller type. 的本地化字符串。
        /// </summary>
        internal static string DirectRoute_MissingControllerType {
            get {
                return ResourceManager.GetString("DirectRoute_MissingControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direct routing does not support per-route route handlers. 的本地化字符串。
        /// </summary>
        internal static string DirectRoute_RouteHandlerNotSupported {
            get {
                return ResourceManager.GetString("DirectRoute_RouteHandlerNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModelType property must not be null. 的本地化字符串。
        /// </summary>
        internal static string EnumHelper_InvalidMetadataParameter {
            get {
                return ResourceManager.GetString("EnumHelper_InvalidMetadataParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string EnumHelper_InvalidParameterType {
            get {
                return ResourceManager.GetString("EnumHelper_InvalidParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value parameter type &apos;{0}&apos;. Must match type parameter &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EnumHelper_InvalidValueParameter {
            get {
                return ResourceManager.GetString("EnumHelper_InvalidValueParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not inherit from Exception. 的本地化字符串。
        /// </summary>
        internal static string ExceptionViewAttribute_NonExceptionType {
            get {
                return ResourceManager.GetString("ExceptionViewAttribute_NonExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The expression compiler was unable to evaluate the indexer expression &apos;{0}&apos; because it references the model parameter &apos;{1}&apos; which is unavailable. 的本地化字符串。
        /// </summary>
        internal static string ExpressionHelper_InvalidIndexerExpression {
            get {
                return ResourceManager.GetString("ExpressionHelper_InvalidIndexerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order must be greater than or equal to -1. 的本地化字符串。
        /// </summary>
        internal static string FilterAttribute_OrderOutOfRange {
            get {
                return ResourceManager.GetString("FilterAttribute_OrderOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The given filter instance must implement one or more of the following filter interfaces: {0}, {1}, {2}, {3}, {4}. 的本地化字符串。
        /// </summary>
        internal static string GlobalFilterCollection_UnsupportedFilterInstance {
            get {
                return ResourceManager.GetString("GlobalFilterCollection_UnsupportedFilterInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The GET and POST HTTP methods are not supported. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_InvalidHttpMethod {
            get {
                return ResourceManager.GetString("HtmlHelper_InvalidHttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified HttpVerbs value is not supported. The supported values are Delete, Head, Put, Options, and Patch. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_InvalidHttpVerb {
            get {
                return ResourceManager.GetString("HtmlHelper_InvalidHttpVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no ViewData item of type &apos;{1}&apos; that has the key &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_MissingSelectData {
            get {
                return ResourceManager.GetString("HtmlHelper_MissingSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; must evaluate to an IEnumerable when multiple selection is allowed. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_SelectExpressionNotEnumerable {
            get {
                return ResourceManager.GetString("HtmlHelper_SelectExpressionNotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value must be greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_TextAreaParameterOutOfRange {
            get {
                return ResourceManager.GetString("HtmlHelper_TextAreaParameterOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ViewData item that has the key &apos;{0}&apos; is of type &apos;{1}&apos; but must be of type &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string HtmlHelper_WrongSelectDataType {
            get {
                return ResourceManager.GetString("HtmlHelper_WrongSelectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The inline constraint resolver of type &apos;{0}&apos; was unable to resolve the following inline constraint: &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string HttpRouteBuilder_CouldNotResolveConstraint {
            get {
                return ResourceManager.GetString("HttpRouteBuilder_CouldNotResolveConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The key is invalid JQuery syntax because it is missing a closing bracket. 的本地化字符串。
        /// </summary>
        internal static string JQuerySyntaxMissingClosingBracket {
            get {
                return ResourceManager.GetString("JQuerySyntaxMissingClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This request has been blocked because sensitive information could be disclosed to third party web sites when this is used in a GET request. To allow GET requests, set JsonRequestBehavior to AllowGet. 的本地化字符串。
        /// </summary>
        internal static string JsonRequest_GetNotAllowed {
            get {
                return ResourceManager.GetString("JsonRequest_GetNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The JSON request was too large to be deserialized. 的本地化字符串。
        /// </summary>
        internal static string JsonValueProviderFactory_RequestTooLarge {
            get {
                return ResourceManager.GetString("JsonValueProviderFactory_RequestTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred when trying to create the IModelBinder &apos;{0}&apos;. Make sure that the binder has a public parameterless constructor. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderAttribute_ErrorCreatingModelBinder {
            get {
                return ResourceManager.GetString("ModelBinderAttribute_ErrorCreatingModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; does not implement the IModelBinder interface. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderAttribute_TypeNotIModelBinder {
            get {
                return ResourceManager.GetString("ModelBinderAttribute_TypeNotIModelBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type &apos;{0}&apos; contains multiple attributes that inherit from CustomModelBinderAttribute. 的本地化字符串。
        /// </summary>
        internal static string ModelBinderDictionary_MultipleAttributes {
            get {
                return ResourceManager.GetString("ModelBinderDictionary_MultipleAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This property setter is obsolete, because its value is derived from ModelMetadata.Model now. 的本地化字符串。
        /// </summary>
        internal static string ModelMetadata_PropertyNotSettable {
            get {
                return ResourceManager.GetString("ModelMetadata_PropertyNotSettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This constructor is obsolete, because its functionality has been moved to MvcForm(ViewContext) now. 的本地化字符串。
        /// </summary>
        internal static string MvcForm_ConstructorObsolete {
            get {
                return ResourceManager.GetString("MvcForm_ConstructorObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;inherits&apos; keyword is not allowed when a &apos;{0}&apos; keyword is used. 的本地化字符串。
        /// </summary>
        internal static string MvcRazorCodeParser_CannotHaveModelAndInheritsKeyword {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_CannotHaveModelAndInheritsKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; keyword must be followed by a type name on the same line. 的本地化字符串。
        /// </summary>
        internal static string MvcRazorCodeParser_ModelKeywordMustBeFollowedByTypeName {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_ModelKeywordMustBeFollowedByTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only one &apos;{0}&apos; statement is allowed in a file. 的本地化字符串。
        /// </summary>
        internal static string MvcRazorCodeParser_OnlyOneModelStatementIsAllowed {
            get {
                return ResourceManager.GetString("MvcRazorCodeParser_OnlyOneModelStatementIsAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The matched route does not include a &apos;controller&apos; route value, which is required. 的本地化字符串。
        /// </summary>
        internal static string MvcRouteHandler_RouteValuesHasNoController {
            get {
                return ResourceManager.GetString("MvcRouteHandler_RouteValuesHasNoController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutputCacheAttribute is not allowed on child actions which are children of an already cached child action. 的本地化字符串。
        /// </summary>
        internal static string OutputCacheAttribute_CannotNestChildCache {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_CannotNestChildCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OutputCacheAttribute for child actions only supports Duration, VaryByCustom, and VaryByParam values. Please do not set CacheProfile, Location, NoStore, SqlDependency, VaryByContentEncoding, or VaryByHeader values for child actions. 的本地化字符串。
        /// </summary>
        internal static string OutputCacheAttribute_ChildAction_UnsupportedSetting {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_ChildAction_UnsupportedSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration must be a positive number. 的本地化字符串。
        /// </summary>
        internal static string OutputCacheAttribute_InvalidDuration {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_InvalidDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VaryByParam must be &apos;*&apos;, &apos;none&apos;, or a semicolon-delimited list of keys. 的本地化字符串。
        /// </summary>
        internal static string OutputCacheAttribute_InvalidVaryByParam {
            get {
                return ResourceManager.GetString("OutputCacheAttribute_InvalidVaryByParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Child actions are not allowed to perform redirect actions. 的本地化字符串。
        /// </summary>
        internal static string RedirectAction_CannotRedirectInChildAction {
            get {
                return ResourceManager.GetString("RedirectAction_CannotRedirectInChildAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create a descriptor for instance method &apos;{0}&apos; on type &apos;{1}&apos; because the type does not derive from ControllerBase. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_CannotCallInstanceMethodOnNonControllerType {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallInstanceMethodOnNonControllerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot call action method &apos;{0}&apos; on controller &apos;{1}&apos; because the parameter &apos;{2}&apos; is passed by reference. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_CannotCallMethodsWithOutOrRefParameters {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallMethodsWithOutOrRefParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot call action method &apos;{0}&apos; on controller &apos;{1}&apos; because the action method is a generic method. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_CannotCallOpenGenericMethods {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallOpenGenericMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot call action method &apos;{0}&apos; on controller &apos;{1}&apos; because the action method is a static method. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_CannotCallStaticMethod {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_CannotCallStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameters dictionary contains a null entry for parameter &apos;{0}&apos; of non-nullable type &apos;{1}&apos; for method &apos;{2}&apos; in &apos;{3}&apos;. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameters dictionary does not contain an entry for parameter &apos;{0}&apos; of type &apos;{1}&apos; for method &apos;{2}&apos; in &apos;{3}&apos;. The dictionary must contain an entry for each parameter, including parameters that have null values. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_ParameterNotInDictionary {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterNotInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameters dictionary contains an invalid entry for parameter &apos;{0}&apos; for method &apos;{1}&apos; in &apos;{2}&apos;. The dictionary contains a value of type &apos;{3}&apos;, but the parameter requires a value of type &apos;{4}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ReflectedActionDescriptor_ParameterValueHasWrongType {
            get {
                return ResourceManager.GetString("ReflectedActionDescriptor_ParameterValueHasWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; on method &apos;{1}&apos; contains multiple attributes that inherit from CustomModelBinderAttribute. 的本地化字符串。
        /// </summary>
        internal static string ReflectedParameterBindingInfo_MultipleConverterAttributes {
            get {
                return ResourceManager.GetString("ReflectedParameterBindingInfo_MultipleConverterAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No url for remote validation could be found. 的本地化字符串。
        /// </summary>
        internal static string RemoteAttribute_NoUrlFound {
            get {
                return ResourceManager.GetString("RemoteAttribute_NoUrlFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is invalid. 的本地化字符串。
        /// </summary>
        internal static string RemoteAttribute_RemoteValidationFailed {
            get {
                return ResourceManager.GetString("RemoteAttribute_RemoteValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested resource can only be accessed via SSL. 的本地化字符串。
        /// </summary>
        internal static string RequireHttpsAttribute_MustUseSsl {
            get {
                return ResourceManager.GetString("RequireHttpsAttribute_MustUseSsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A path segment that contains more than one section, such as a literal section or a parameter, cannot contain a catch-all parameter. 的本地化字符串。
        /// </summary>
        internal static string Route_CannotHaveCatchAllInMultiSegment {
            get {
                return ResourceManager.GetString("Route_CannotHaveCatchAllInMultiSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A path segment cannot contain two consecutive parameters. They must be separated by a &apos;/&apos; or by a literal string. 的本地化字符串。
        /// </summary>
        internal static string Route_CannotHaveConsecutiveParameters {
            get {
                return ResourceManager.GetString("Route_CannotHaveConsecutiveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The route template separator character &apos;/&apos; cannot appear consecutively. It must be separated by either a parameter or a literal value. 的本地化字符串。
        /// </summary>
        internal static string Route_CannotHaveConsecutiveSeparators {
            get {
                return ResourceManager.GetString("Route_CannotHaveConsecutiveSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A catch-all parameter can only appear as the last segment of the route template. 的本地化字符串。
        /// </summary>
        internal static string Route_CatchAllMustBeLast {
            get {
                return ResourceManager.GetString("Route_CatchAllMustBeLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The constraint entry &apos;{0}&apos; on the route with route template &apos;{1}&apos; must have a string value or be of a type which implements &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Route_InvalidConstraint {
            get {
                return ResourceManager.GetString("Route_InvalidConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The route parameter name &apos;{0}&apos; is invalid. Route parameter names must be non-empty and cannot contain these characters: &quot;{{&quot;, &quot;}}&quot;, &quot;/&quot;, &quot;?&quot; 的本地化字符串。
        /// </summary>
        internal static string Route_InvalidParameterName {
            get {
                return ResourceManager.GetString("Route_InvalidParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The route template cannot start with a &apos;/&apos; or &apos;~&apos; character and it cannot contain a &apos;?&apos; character. 的本地化字符串。
        /// </summary>
        internal static string Route_InvalidRouteTemplate {
            get {
                return ResourceManager.GetString("Route_InvalidRouteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is an incomplete parameter in this path segment: &apos;{0}&apos;. Check that each &apos;{{&apos; character has a matching &apos;}}&apos; character. 的本地化字符串。
        /// </summary>
        internal static string Route_MismatchedParameter {
            get {
                return ResourceManager.GetString("Route_MismatchedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The route parameter name &apos;{0}&apos; appears more than one time in the route template. 的本地化字符串。
        /// </summary>
        internal static string Route_RepeatedParameter {
            get {
                return ResourceManager.GetString("Route_RepeatedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The prefix &apos;{0}&apos; of the route area named &apos;{1}&apos; on the controller named &apos;{2}&apos; cannot end with a forward slash. 的本地化字符串。
        /// </summary>
        internal static string RouteAreaPrefix_CannotEnd_WithForwardSlash {
            get {
                return ResourceManager.GetString("RouteAreaPrefix_CannotEnd_WithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The route prefix &apos;{0}&apos; on the controller named &apos;{1}&apos; cannot begin or end with a forward slash. 的本地化字符串。
        /// </summary>
        internal static string RoutePrefix_CannotStartOrEnd_WithForwardSlash {
            get {
                return ResourceManager.GetString("RoutePrefix_CannotStartOrEnd_WithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only one route prefix attribute is supported. Remove extra attributes from the controller of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string RoutePrefix_CannotSupportMultiRoutePrefix {
            get {
                return ResourceManager.GetString("RoutePrefix_CannotSupportMultiRoutePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The property &apos;prefix&apos; from route prefix attribute on controller of type &apos;{0}&apos; cannot be null. 的本地化字符串。
        /// </summary>
        internal static string RoutePrefix_PrefixCannotBeNull {
            get {
                return ResourceManager.GetString("RoutePrefix_PrefixCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The route template &apos;{0}&apos; on the action named &apos;{1}&apos; on the controller named &apos;{2}&apos; cannot begin with a forward slash. 的本地化字符串。
        /// </summary>
        internal static string RouteTemplate_CannotStart_WithForwardSlash {
            get {
                return ResourceManager.GetString("RouteTemplate_CannotStart_WithForwardSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to determine ModelMetadata for expression &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string SelectExtensions_InvalidExpressionParameterNoMetadata {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterNoMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to determine type of expression &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string SelectExtensions_InvalidExpressionParameterNoModelType {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterNoModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return type &apos;{0}&apos; is not supported. 的本地化字符串。
        /// </summary>
        internal static string SelectExtensions_InvalidExpressionParameterType {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return type &apos;{0}&apos; is not supported. Type must not have a &apos;{1}&apos; attribute. 的本地化字符串。
        /// </summary>
        internal static string SelectExtensions_InvalidExpressionParameterTypeHasFlags {
            get {
                return ResourceManager.GetString("SelectExtensions_InvalidExpressionParameterTypeHasFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The SessionStateTempDataProvider class requires session state to be enabled. 的本地化字符串。
        /// </summary>
        internal static string SessionStateTempDataProvider_SessionStateDisabled {
            get {
                return ResourceManager.GetString("SessionStateTempDataProvider_SessionStateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An instance of {0} was found in the resolver as well as a custom registered provider in {1}. Please set only one or the other. 的本地化字符串。
        /// </summary>
        internal static string SingleServiceResolver_CannotRegisterTwoInstances {
            get {
                return ResourceManager.GetString("SingleServiceResolver_CannotRegisterTwoInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A route named &apos;{0}&apos; is already in the route collection. Route names must be unique.
        ///
        ///Duplicates:
        ///{1}
        ///{2} 的本地化字符串。
        /// </summary>
        internal static string SubRouteCollection_DuplicateRouteName {
            get {
                return ResourceManager.GetString("SubRouteCollection_DuplicateRouteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An operation that crossed a synchronization context failed. See the inner exception for more information. 的本地化字符串。
        /// </summary>
        internal static string SynchronizationContextUtil_ExceptionThrown {
            get {
                return ResourceManager.GetString("SynchronizationContextUtil_ExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The asynchronous action method &apos;{0}&apos; returns a Task, which cannot be executed synchronously. 的本地化字符串。
        /// </summary>
        internal static string TaskAsyncActionDescriptor_CannotExecuteSynchronously {
            get {
                return ResourceManager.GetString("TaskAsyncActionDescriptor_CannotExecuteSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to locate an appropriate template for type {0}. 的本地化字符串。
        /// </summary>
        internal static string TemplateHelpers_NoTemplate {
            get {
                return ResourceManager.GetString("TemplateHelpers_NoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Templates can be used only with field access, property access, single-dimension array index, or single-parameter custom indexer expressions. 的本地化字符串。
        /// </summary>
        internal static string TemplateHelpers_TemplateLimitations {
            get {
                return ResourceManager.GetString("TemplateHelpers_TemplateLimitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Collection template was used with an object of type &apos;{0}&apos;, which does not implement System.IEnumerable. 的本地化字符串。
        /// </summary>
        internal static string Templates_TypeMustImplementIEnumerable {
            get {
                return ResourceManager.GetString("Templates_TypeMustImplementIEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file is automatically generated. Please do not modify the contents of this file. 的本地化字符串。
        /// </summary>
        internal static string TypeCache_DoNotModify {
            get {
                return ResourceManager.GetString("TypeCache_DoNotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Object type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TypeHelpers_CannotCreateInstance {
            get {
                return ResourceManager.GetString("TypeHelpers_CannotCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}.{1} must not return null. 的本地化字符串。
        /// </summary>
        internal static string TypeMethodMustNotReturnNull {
            get {
                return ResourceManager.GetString("TypeMethodMustNotReturnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model object inside the metadata claimed to be compatible with {0}, but was actually {1}. 的本地化字符串。
        /// </summary>
        internal static string ValidatableObjectAdapter_IncompatibleType {
            get {
                return ResourceManager.GetString("ValidatableObjectAdapter_IncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter conversion from type &apos;{0}&apos; to type &apos;{1}&apos; failed. See the inner exception for more information. 的本地化字符串。
        /// </summary>
        internal static string ValueProviderResult_ConversionThrew {
            get {
                return ResourceManager.GetString("ValueProviderResult_ConversionThrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter conversion from type &apos;{0}&apos; to type &apos;{1}&apos; failed because no type converter can convert between these types. 的本地化字符串。
        /// </summary>
        internal static string ValueProviderResult_NoConverterExists {
            get {
                return ResourceManager.GetString("ValueProviderResult_NoConverterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model item passed into the dictionary is null, but this dictionary requires a non-null model item of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ViewDataDictionary_ModelCannotBeNull {
            get {
                return ResourceManager.GetString("ViewDataDictionary_ModelCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The model item passed into the dictionary is of type &apos;{0}&apos;, but this dictionary requires a model item of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ViewDataDictionary_WrongTModelType {
            get {
                return ResourceManager.GetString("ViewDataDictionary_WrongTModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A ViewMasterPage can be used only with content pages that derive from ViewPage or ViewPage&lt;TModel&gt;. 的本地化字符串。
        /// </summary>
        internal static string ViewMasterPage_RequiresViewPage {
            get {
                return ResourceManager.GetString("ViewMasterPage_RequiresViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution of the child request failed. Please examine the InnerException for more information. 的本地化字符串。
        /// </summary>
        internal static string ViewPageHttpHandlerWrapper_ExceptionOccurred {
            get {
                return ResourceManager.GetString("ViewPageHttpHandlerWrapper_ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A ViewStartPage can be used only with with a page that derives from WebViewPage or another ViewStartPage. 的本地化字符串。
        /// </summary>
        internal static string ViewStartPage_RequiresMvcRazorView {
            get {
                return ResourceManager.GetString("ViewStartPage_RequiresMvcRazorView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The ViewUserControl &apos;{0}&apos; cannot find an IViewDataContainer object. The ViewUserControl must be inside a ViewPage, a ViewMasterPage, or another ViewUserControl. 的本地化字符串。
        /// </summary>
        internal static string ViewUserControl_RequiresViewDataProvider {
            get {
                return ResourceManager.GetString("ViewUserControl_RequiresViewDataProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A ViewUserControl can be used only in pages that derive from ViewPage or ViewPage&lt;TModel&gt;. 的本地化字符串。
        /// </summary>
        internal static string ViewUserControl_RequiresViewPage {
            get {
                return ResourceManager.GetString("ViewUserControl_RequiresViewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A master name cannot be specified when the view is a ViewUserControl. 的本地化字符串。
        /// </summary>
        internal static string WebFormViewEngine_UserControlCannotHaveMaster {
            get {
                return ResourceManager.GetString("WebFormViewEngine_UserControlCannotHaveMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The view at &apos;{0}&apos; must derive from ViewPage, ViewPage&lt;TModel&gt;, ViewUserControl, or ViewUserControl&lt;TModel&gt;. 的本地化字符串。
        /// </summary>
        internal static string WebFormViewEngine_WrongViewBase {
            get {
                return ResourceManager.GetString("WebFormViewEngine_WrongViewBase", resourceCulture);
            }
        }
    }
}
